# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: metallb-shared
#   namespace: argocd
# spec:
#   project: platform
#   source:
#     repoURL: https://github.com/aditya0301/k8s-homelab.git
#     targetRevision: main
#     path: metalLB/k8s/overlays/shared
#   destination:
#     name: in-cluster
#     namespace: argocd
#   syncPolicy:
#     automated: {}


